// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	client "azure.com/novek/awesomeProject/interfaces/client"
	mock "github.com/stretchr/testify/mock"
)

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

// Request provides a mock function with given fields: urls
func (_m *IClient) Request(urls []string) []client.URLResponse {
	ret := _m.Called(urls)

	var r0 []client.URLResponse
	if rf, ok := ret.Get(0).(func([]string) []client.URLResponse); ok {
		r0 = rf(urls)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.URLResponse)
		}
	}

	return r0
}

type mockConstructorTestingTNewIClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewIClient creates a new instance of IClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIClient(t mockConstructorTestingTNewIClient) *IClient {
	mock := &IClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
